package api

const (
	LUA_TNONE = iota - 1 // Lua 栈按索引取值时, 若是一个无效索引, 那么则返回该值
	LUA_TNIL
	LUA_TBOOLEAN
	LUA_TLIGHTUSERDATA
	LUA_TNUMBER
	LUA_TSTRING
	LUA_TTABLE
	LUA_TFUNCTION
	LUA_TUSERDATA
	LUA_TTHREAD
)